# Generated by Django 5.0 on 2024-04-14 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0004_rename_comment_komentarz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentarz',
            name='Temat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentarze', to='Forum.temat'),
        ),
    ]
