# Generated by Django 5.0 on 2024-05-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0007_alter_komentarz_autor_alter_temat_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentarz',
            name='Tekst',
            field=models.TextField(max_length=255),
        ),
    ]
