# Generated by Django 5.0 on 2024-05-10 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0008_alter_komentarz_tekst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='temat',
            name='Status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Forum.status'),
        ),
    ]
