# Generated by Django 5.0 on 2024-05-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0009_status_temat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='Nazwa',
            field=models.CharField(default='Otwarty', max_length=50),
        ),
    ]
