# Generated by Django 5.0 on 2024-05-10 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0010_alter_status_nazwa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temat',
            name='Status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
