# Generated by Django 5.0 on 2024-05-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0012_status_temat_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temat',
            name='Status',
        ),
        migrations.AlterField(
            model_name='status',
            name='Nazwa',
            field=models.TextField(max_length=10, unique=True),
        ),
    ]
