# Generated by Django 5.0 on 2024-05-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0013_remove_temat_status_alter_status_nazwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='Nazwa',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
