# Generated by Django 5.0 on 2023-12-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tytuł', models.CharField(max_length=255)),
                ('Kategoria', models.CharField(max_length=255)),
                ('Opis', models.CharField(max_length=255)),
            ],
        ),
    ]
