# Generated by Django 5.0 on 2023-12-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collectors_Zone', '0004_alter_kategoria_nazwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Opis',
            field=models.TextField(),
        ),
    ]
