# Generated by Django 5.0 on 2024-03-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collectors_Zone', '0005_alter_post_opis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa', models.CharField(max_length=255)),
                ('Opis', models.CharField(max_length=255)),
                ('Data', models.DateTimeField()),
            ],
        ),
    ]
