# Generated by Django 5.0 on 2024-03-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collectors_Zone', '0006_drop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drop',
        ),
    ]
