# Generated by Django 5.0 on 2024-03-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_site', '0007_delete_drop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tytuł', models.CharField(max_length=255)),
                ('Strona', models.CharField(max_length=255)),
                ('Data', models.DateTimeField()),
            ],
        ),
    ]
