# Generated by Django 5.0 on 2024-03-12 11:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_site', '0008_drop'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='Godzina',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drop',
            name='Data',
            field=models.DateField(),
        ),
    ]
