# Generated by Django 5.0 on 2024-03-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_site', '0009_drop_godzina_alter_drop_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='Cena',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
