# Generated by Django 5.0 on 2024-03-13 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_site', '0010_drop_cena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='drop',
            name='Typ',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main_site.typ'),
            preserve_default=False,
        ),
    ]
