# Generated by Django 5.0 on 2024-03-13 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_site', '0012_remove_post_kategoria_delete_kategoria_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drop',
        ),
        migrations.DeleteModel(
            name='Typ',
        ),
    ]
