# Generated by Django 5.0 on 2024-03-14 08:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dropy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='Zdjęcia',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/images/'),
            preserve_default=False,
        ),
    ]
