# Generated by Django 5.0 on 2024-03-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dropy', '0002_drop_zdjęcia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drop',
            name='Zdjęcia',
            field=models.ImageField(upload_to='drops_images'),
        ),
    ]
