# Generated by Django 5.0 on 2024-05-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dropy', '0004_alter_drop_zdjęcia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drop',
            name='Zdjęcia',
            field=models.ImageField(blank=True, null=True, upload_to='drops_images/'),
        ),
    ]
