# Generated by Django 5.0 on 2024-05-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Zdjęcia',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
