# Generated by Django 5.0 on 2024-03-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Użytkownicy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
