# Generated by Django 5.0 on 2024-03-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Użytkownicy', '0004_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
